import { Info } from 'lucide-react';

interface DisclaimerProps {
  className?: string;
}

export const Disclaimer: React.FC<DisclaimerProps> = ({ className = '' }) => {
  return (
    <div className={`rounded-xl bg-slate-900/60 border border-slate-800 p-4 text-xs text-slate-400 ${className}`}>
      <div className="flex items-start gap-3">
        <Info className="w-4 h-4 text-cyan-400 flex-shrink-0 mt-0.5" />
        <div className="space-y-1">
          <div className="font-semibold text-slate-300 flex items-center gap-2">
            <span>Maritime Legal & Regulatory Notice — AI-Assisted Intelligence</span>
            <span className="text-[9px] px-1.5 py-0.2 rounded bg-cyan-950 text-cyan-400 border border-cyan-800 font-mono">
              MARPOL 73/78
            </span>
          </div>
          <p className="leading-relaxed">
            Attribution scores and forensic indicators generated by Ocean Sentinel are probabilistic decision-support outputs based on satellite radar anomaly segmentation and historical AIS transponder telemetry. These findings are intended to assist Coast Guard inspection planning, port state control audits, and environmental tribunal investigations, and do not constitute self-executing legal judgments of liability.
          </p>
        </div>
      </div>
    </div>
  );
};
