import React, { useState } from 'react';
import { 
  HelpCircle, 
  ChevronDown, 
  ChevronUp, 
  BookOpen, 
  Satellite
} from 'lucide-react';

export const HelpPage: React.FC = () => {
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const faqs = [
    {
      q: 'How does synthetic aperture radar (SAR) detect oil spills at night and through clouds?',
      a: 'Synthetic aperture radar operates in the microwave spectrum (C-band 5.4 GHz on Sentinel-1). Unlike optical cameras, microwave pulses penetrate clouds, rain, and fog with zero atmospheric attenuation and do not rely on solar illumination. Capillary ripples on the sea surface normally scatter radar energy back to the antenna. When petroleum or oily wastewater covers the surface, it increases surface tension and dampens these capillary wavelets, causing microwave pulses to reflect specularly away from the satellite, appearing as characteristic "dark surface anomalies".'
    },
    {
      q: 'How does the AI model distinguish petroleum spills from natural biogenic lookalikes?',
      a: 'Natural marine algae, fish oils, and low-wind calm zones can also dampen capillary waves. Ocean Sentinel uses a deep convolutional UNet neural network trained on multi-spectral texture contrast, slick boundary gradients, aspect ratio elongation, and ECMWF real-time surface wind fields (validating that local winds are within the 3 - 12 m/s SAR detection envelope).'
    },
    {
      q: 'What occurs if a suspect vessel disables its AIS transponder (dark vessel activity)?',
      a: 'The AIS backtracking engine tracks transponder signal continuity across a 72-hour historical window. If a vessel abruptly ceases broadcasting while transiting through the slick corridor and reappears down-current, the platform flags an "AIS Continuity Anomaly", which is incorporated as a high-severity circumstantial indicator in the forensic dossier.'
    },
    {
      q: 'How are attribution scores mathematically computed?',
      a: 'The overall attribution score is a weighted composite of four forensic criteria: Spatial Proximity to slick center (30%), Temporal Correlation with slick weathering age (25%), Trajectory Alignment with ocean current drift vector (25%), and AIS Signal Integrity (20%). Operators can calibrate these weights dynamically in the Attribution Studio.'
    },
    {
      q: 'What legal enforcement actions can the Coast Guard take with an Ocean Sentinel dossier?',
      a: 'Dossiers generated by Ocean Sentinel comply with MARPOL 73/78 Annex I (Regulations for the Prevention of Pollution by Oil). The Coast Guard can dispatch Fast Interceptor Craft for maritime sampling, notify Port State Control at the destination port to inspect the Oil Record Book, and file official charges under the Merchant Shipping Act.'
    }
  ];

  return (
    <div className="space-y-8 pb-16 max-w-4xl mx-auto">
      {/* Header */}
      <div className="border-b border-slate-200 dark:border-slate-800 pb-5">
        <div className="flex items-center gap-2 mb-1">
          <HelpCircle className="w-4 h-4 text-cyan-600 dark:text-cyan-400" />
          <span className="text-xs font-mono font-bold text-cyan-600 dark:text-cyan-400 uppercase tracking-widest">
            Operator Support & Documentation
          </span>
        </div>
        <h1 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white tracking-tight">
          Platform Knowledge Base & Reference Manual
        </h1>
        <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-400 mt-1">
          Standard operating procedures, forensic methodology, and operational quick reference
        </p>
      </div>

      {/* FAQ Accordion */}
      <div className="space-y-3">
        <div className="flex items-center gap-2 pb-2">
          <BookOpen className="w-4 h-4 text-cyan-600 dark:text-cyan-400" />
          <h2 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider">
            Frequently Asked Operational Questions
          </h2>
        </div>

        {faqs.map((faq, idx) => {
          const isOpen = openFaq === idx;
          return (
            <div
              key={idx}
              className="rounded-xl bg-white dark:bg-[#111827] border border-slate-200 dark:border-slate-800 overflow-hidden transition shadow-xs"
            >
              <button
                onClick={() => setOpenFaq(isOpen ? null : idx)}
                className="w-full p-4 flex items-center justify-between text-left text-xs sm:text-sm font-semibold text-slate-900 dark:text-slate-200 hover:text-cyan-600 dark:hover:text-cyan-300 transition"
              >
                <span>{faq.q}</span>
                {isOpen ? <ChevronUp className="w-4 h-4 text-cyan-600 dark:text-cyan-400 flex-shrink-0 ml-2" /> : <ChevronDown className="w-4 h-4 text-slate-400 dark:text-slate-500 flex-shrink-0 ml-2" />}
              </button>

              {isOpen && (
                <div className="px-4 pb-4 text-xs text-slate-600 dark:text-slate-400 leading-relaxed border-t border-slate-100 dark:border-slate-800/80 pt-3">
                  {faq.a}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Sensor Specifications Table */}
      <div className="rounded-xl bg-white dark:bg-[#111827] border border-slate-200 dark:border-slate-800 p-5 shadow-xs dark:shadow-xl space-y-3 transition-colors">
        <div className="flex items-center gap-2 pb-2 border-b border-slate-200 dark:border-slate-800">
          <Satellite className="w-4 h-4 text-cyan-600 dark:text-cyan-400" />
          <h3 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider">
            Copernicus Constellation Specifications
          </h3>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left font-mono">
            <thead className="text-[10px] text-slate-500 dark:text-slate-400 uppercase border-b border-slate-200 dark:border-slate-800 bg-slate-50/60 dark:bg-transparent">
              <tr>
                <th className="py-2.5 px-3 font-semibold">Satellite</th>
                <th className="py-2.5 px-3 font-semibold">Payload Sensor</th>
                <th className="py-2.5 px-3 font-semibold">Frequency / Band</th>
                <th className="py-2.5 px-3 font-semibold">Spatial Resolution</th>
                <th className="py-2.5 px-3 font-semibold">Swath Width</th>
                <th className="py-2.5 px-3 font-semibold">Revisit Time</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 text-slate-700 dark:text-slate-300">
              <tr>
                <td className="py-2.5 px-3 font-bold text-cyan-700 dark:text-cyan-400">Sentinel-1A/B</td>
                <td className="py-2.5 px-3 font-sans">C-band SAR</td>
                <td className="py-2.5 px-3">5.405 GHz</td>
                <td className="py-2.5 px-3 font-bold text-emerald-600 dark:text-emerald-400">10m (IW Mode)</td>
                <td className="py-2.5 px-3">250 km</td>
                <td className="py-2.5 px-3 font-sans">6 days (Constellation)</td>
              </tr>
              <tr>
                <td className="py-2.5 px-3 font-bold text-blue-600 dark:text-blue-400">Sentinel-2A/B</td>
                <td className="py-2.5 px-3 font-sans">MSI Multi-Spectral</td>
                <td className="py-2.5 px-3">13 Spectral Bands</td>
                <td className="py-2.5 px-3 font-bold text-cyan-700 dark:text-cyan-400">10m / 20m</td>
                <td className="py-2.5 px-3">290 km</td>
                <td className="py-2.5 px-3 font-sans">5 days (Cloud dependent)</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Hackathon Attribution Card */}
      <div className="p-6 rounded-xl bg-gradient-to-r from-cyan-50 via-white to-blue-50 dark:from-cyan-950/40 dark:via-slate-900 dark:to-blue-950/40 border border-cyan-200 dark:border-cyan-500/30 flex flex-col sm:flex-row sm:items-center justify-between gap-4 shadow-xs dark:shadow-md">
        <div>
          <div className="text-xs font-mono font-bold text-cyan-600 dark:text-cyan-400 mb-1">SMART INDIA HACKATHON 2026</div>
          <div className="text-base font-bold text-slate-900 dark:text-white">Developed by Team omegaSquad</div>
          <p className="text-xs text-slate-600 dark:text-slate-400 mt-0.5">
            Ministry of Defense / Indian Coast Guard Problem Statement: AI-Powered Oil Spill Detection & Attribution
          </p>
        </div>
        <div className="text-xs text-slate-500 dark:text-slate-400 font-mono">
          Release Version: <strong className="text-slate-900 dark:text-slate-200">v2.4.0-production</strong>
        </div>
      </div>
    </div>
  );
};

export default HelpPage;
